[project]
name = "techjam25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "fasttext>=0.9.3",
    "ipykernel>=6.30.1",
    "loguru>=0.7.3",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
    "torch>=2.8.0",
    "transformers>=4.55.4",
]
