[project]
name = "rudys-rangers-techjam25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "huggingface-hub>=0.34.4",
    "peft>=0.17.1",
    "torch>=2.8.0",
    "transformers>=4.55.4",
]
