# safety_pipeline:
# tfidf:
# min_df: [3, 5, 10, 20]
# max_features: [25000, 50000, 75000]
# ngram_range: [1, 2]

# lexicon:
# enabled: [true, false]

# clf:
# class_weight: balanced
#    max_iter: [500, 1000, 2000]

safety_pipeline:
  tfidf:
    min_df: 10
    max_features: 75000
    ngram_range: [1, 2]
  lexicon:
    enabled: true

  clf:
    class_weight: balanced
    max_iter: 2000
